# Generated by Django 5.2.7 on 2025-11-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reply',
            field=models.TextField(default=True, null=True),
        ),
    ]
