# Generated by Django 5.2.7 on 2025-11-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
    ]
