# Generated by Django 5.2.7 on 2025-11-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_generated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
